# Generated by Django 2.0.7 on 2018-07-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180714_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='enable',
        ),
    ]
